// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

((require('./square.css')));

function getClass(gameState, value) {
  if (typeof gameState === "number" || !gameState.tag) {
    return "";
  } else if (gameState[0]) {
    if (value === /* Marked */[/* Cross */1]) {
      return "green";
    } else {
      return "";
    }
  } else if (value === /* Marked */[/* Circle */0]) {
    return "green";
  } else {
    return "";
  }
}

function isFinished(gameState) {
  if (typeof gameState === "number" || gameState.tag) {
    return true;
  } else {
    return false;
  }
}

function drawField(field) {
  if (field) {
    if (field[0]) {
      return "X";
    } else {
      return "O";
    }
  } else {
    return "";
  }
}

var component = ReasonReact.statelessComponent("Square");

function make(value, gameState, onMark, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("button", {
                          className: "BoardCell" + getClass(gameState, value),
                          disabled: isFinished(gameState),
                          onClick: (function (_evt) {
                              return Curry._1(onMark, /* () */0);
                            })
                        }, drawField(value));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.getClass = getClass;
exports.isFinished = isFinished;
exports.drawField = drawField;
exports.component = component;
exports.make = make;
/*  Not a pure module */
